// col reader of TheTestLass, generated by github.com/khicago/got/table2d/preset/cmd
package main

import (
	"github.com/khicago/got/table2d/preset"
	"github.com/khicago/got/table2d/preset/pcol"
)

type TheTestLass struct {
	ch *pcol.ColHeader
}

func NewTheTestLass(ch *pcol.ColHeader) *TheTestLass {
	return &TheTestLass{ch: ch}
}

func (p *TheTestLass) PHeader() *pcol.ColHeader {
	return p.ch
}

// ============= code block of LvUp =============

// MetaOfLvUp returns ColMeta of LvUp
func (p *TheTestLass) MetaOfLvUp() *pcol.ColMeta {
	return p.ch.Get(1)
}

// LvUp reads the value of LvUp
func (p *TheTestLass) LvUp(prop preset.IProp) (int64, error) {
	seal := prop.Get(1)
	return seal.ID()
}

// ============= code block of Magic =============

// MetaOfMagic returns ColMeta of Magic
func (p *TheTestLass) MetaOfMagic() *pcol.ColMeta {
	return p.ch.Get(3)
}

// Magic reads the value of Magic
func (p *TheTestLass) Magic(prop preset.IProp) (float64, error) {
	seal := prop.Get(3)
	return seal.Float()
}

// ============= code block of Pid =============

// MetaOfPid returns ColMeta of Pid
func (p *TheTestLass) MetaOfPid() *pcol.ColMeta {
	return p.ch.Get(0)
}

// Pid reads the value of Pid
func (p *TheTestLass) Pid(prop preset.IProp) (int64, error) {
	seal := prop.Get(0)
	return seal.PID()
}

// ============= code block of Power =============

// MetaOfPower returns ColMeta of Power
func (p *TheTestLass) MetaOfPower() *pcol.ColMeta {
	return p.ch.Get(2)
}

// Power reads the value of Power
func (p *TheTestLass) Power(prop preset.IProp) (int, error) {
	seal := prop.Get(2)
	return seal.Int()
}
